version: '3.1'

services:

  db:
    image: postgres
    container_name: blogdb
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: chat_admin
      POSTGRES_PASSWORD: 125436
      POSTGRES_DB: chatroom_db

  adminer:
    image: adminer
    container_name: adminer
    links:
      - db
    ports:
      - 8080:8080