default: &default
  adapter: postgresql
  host: 127.0.0.1
  port: 5433
  encoding: unicode
  database: blog_db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: blog_admin
  password: 125436
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
